# Mod lucru cu Matrici in Python

## Utilizarea Pachetului NumPy

### Instalare si import NumPy


Instalare (doar daca este cazul - teoretic este instalat odata cu Anaconda):  
    
    pip install numpy
    
Import pachet: 

    import numpy as np

> ___Numpy___ contine multe functii si capabilitați incorporate. Nu o sa le acoperim pe toate in acest tutorial, dar ne vom concentra pe cateva dintre cele mai importante: vectori, matrici si generarea automata de matrici.


In [1]:
# Odata ce NumPy este instalat il putem importa ca o librarie
import numpy as np 

### Definirea unei variabile de tip matrice

In [2]:
# Atribuirea unei liste de valori
my_list = [1, 2, 4, 5, 6] # Python List
print("Python List: ", my_list) 

# Conversia unei liste ca NumPy Array 
my_matrix = np.array(my_list) # Create an array by directly converting a list 
print("NumPy Array: ", my_matrix) 

Python List:  [1, 2, 4, 5, 6]
NumPy Array:  [1 2 4 5 6]


In [5]:
# Definirea unei matrici ca lista de liste
my_matrix = np.array( [[1,2,3],[4,5,6],[7,8,9]] ) # create an array by converting a list of lists

# afisare variabila definita anterior direct 
# (doar o variabila pe celula se poate afisa asa)
my_matrix

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [6]:
# afisare variabila definita anterior folosind print 
# (se pot afisa oricate variabile pe celula utilizand print)
print(my_matrix)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


### Operatii artimetice intre matrici si scalar 
- adunare, scadere, inmultire si impartire a unei matrici cu scalar
        + adunare; - scadere;
        * inmultire; / impartire; 
        ** ridicare la patrat

In [7]:
# Operatii aritmetice cu scalari 
# Vom exemplifica doar adunarea si inmultirea

print ("Matricea originala: \n", my_matrix)

mtx_add_sc = my_matrix + 7 # Add scalar
print ("Adunare cu un scalar: \n", mtx_add_sc)

mtx_mult_sc = my_matrix * 2 # Inmultire cu un scalar
print ("Inmultire cu un scalar: \n", mtx_mult_sc)

Matricea originala: 
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
Adunare cu un scalar: 
 [[ 8 11 14]
 [ 9 12 15]
 [10 13 16]]
Inmultire cu un scalar: 
 [[ 2  4  6]
 [ 8 10 12]
 [14 16 18]]


### Operatii artimetice intre matrici
- adunare si inmultire intre matrici

In [11]:
# Operatii aritmetice intre matrici

# Adunare si scadere intre matrici
mtx_add_mtx = my_matrix + my_matrix 
mtx_sub_mtx = my_matrix - my_matrix
print("mtx_add_mtx: \n", mtx_add_mtx)
print("mtx_sub_mtx: \n", mtx_sub_mtx)

# Inmultire si impartire (pozitie cu pozitie) intre matrici
mtx_mult_pct = my_matrix * my_matrix # sau: np.multiply(my_matrix, my_matrix)
mtx_div_pct = my_matrix / my_matrix
print("mtx_mult_pct: \n", mtx_mult_pct)
print("mtx_mult_pct: \n", mtx_div_pct)

# Inmultire intre matrici 
mtx_mult_mtx = np.dot(my_matrix, my_matrix)
print("mtx_mult_mtx: \n", mtx_mult_mtx)

# Atentie!!! 
#     La impartirea cu zero va aparea o avertizare dar nu e o eroare
#     Se va inlocui rezultatul cu Nan 


mtx_add_mtx: 
 [ 2  4  8 10 12]
mtx_sub_mtx: 
 [0 0 0 0 0]
mtx_mult_pct: 
 [ 1  4 16 25 36]
mtx_mult_pct: 
 [1. 1. 1. 1. 1.]
mtx_mult_mtx: 
 82


### Metode NumPy incorporate - pentru a genera automat matrici 

Built-in Methods to generate Arrays

In [12]:
# Generate arrays of zeros 
mtx_zeros_1D = np.zeros(3) 
mtx_zeros_2D = np.zeros((5,5)) 
print("Generarea unui vector 1D de zerouri: \n", mtx_zeros_1D)
print("Generarea unei matrici 2D de zerouri: \n", mtx_zeros_2D)

# Generate arrays of ones
mtx_ones_1D = np.ones(3)
mtx_ones_2D = np.ones((3,3))
print("Generarea unui vector 1D de unu: \n", mtx_ones_1D)
print("Generarea unei matrici 2D de unu: \n", mtx_ones_2D)

# Creates an identity matrix
mtx_eyes_2D = np.eye(4) 
print("Generarea unei matrici 2D identitate: \n", mtx_eyes_2D)

Generarea unui vector 1D de zerouri: 
 [0. 0. 0.]
Generarea unei matrici 2D de zerouri: 
 [[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]
Generarea unui vector 1D de unu: 
 [1. 1. 1.]
Generarea unei matrici 2D de unu: 
 [[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
Generarea unei matrici 2D identitate: 
 [[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [21]:
# Generarea unui vector cu toate valorile dintr-un interval
mtx_arange_all = np.arange(0,10)
mtx_arange_step = np.arange(0,10,2) # cu specificarea pasului de scanare
print(" -- Generare vector cu valori dintr-un interval dat, cu un pas de scanare  --")
print(" Pasul de scanare este default 1: \n", mtx_arange_all)
print(" Pasul de scanare a fost specificat ca si parametru: \n", mtx_arange_step)

 -- Generare vector cu valori dintr-un interval dat --
 Pasul de scanare este default 1: 
 [0 1 2 3 4 5 6 7 8 9]
 Pasul de scanare a fost specificat ca si parametru: 
 [0 2 4 6 8]


In [24]:
# Return evenly spaced numbers over a specified interval.
print("-- Generare vector cu valori dintr-un interval dat, cu specificarea numarului de valori dorite la iesire --")
mtx_linspace_less = np.linspace(0,10,3)
mtx_linspace_more = np.linspace(0,10,10)

print("Exemplificare linspace cu putine valori: \n", mtx_linspace_less)
print("Exemplificare linspace cu mai multe valori: \n", mtx_linspace_more)

-- Generare vector cu valori dintr-un interval dat, cu specificarea numarului de valori dorite la iesire --
Exemplificare linspace cu putine valori: 
 [ 0.  5. 10.]
Exemplificare linspace cu mai multe valori: 
 [ 0.          1.11111111  2.22222222  3.33333333  4.44444444  5.55555556
  6.66666667  7.77777778  8.88888889 10.        ]


In [26]:
# rand - Create an array of the given shape 
#       and populate it with random samples from a uniform distribution over [0, 1].
mtx_rand_1D = np.random.rand(2) # 1D
mtx_rand_2D = np.random.rand(5,5) # 2D

print("mtx_rand_1D: \n", mtx_rand_1D)
print("mtx_rand_2D: \n", mtx_rand_2D)

# randn - Return a sample (or samples) from the "standard normal" distribution. 
#         Unlike rand which is uniform
mtx_randn_1D = np.random.randn(4) 
mtx_randn_2D = np.random.randn(5,5)

print("mtx_randn_1D: \n", mtx_randn_1D)
print("mtx_randn_2D: \n", mtx_randn_2D)

# randint - Return random integers from low (inclusive) to high (exclusive).
rdnint_one = np.random.randint(1,100)
rdnint_more = np.random.randint(1,100,10)

print("rdnint_one: \n", rdnint_one)
print("rdnint_more: \n", rdnint_more)

mtx_rand_1D: 
 [0.73840992 0.03769252]
mtx_rand_2D: 
 [[0.05690193 0.27331794 0.09683582 0.06936504 0.57594841]
 [0.86164822 0.69558072 0.53818638 0.67302655 0.32250581]
 [0.62666949 0.35089751 0.37272086 0.44118075 0.52509122]
 [0.76760519 0.17048833 0.78894655 0.86335375 0.61905264]
 [0.99981792 0.55821942 0.85524534 0.24438102 0.77953916]]
mtx_randn_1D: 
 [-0.50348928  0.30261045 -0.43249584 -0.29105752]
mtx_randn_2D: 
 [[ 0.62353679  0.69421881 -0.93557059  2.11019902 -1.15761685]
 [-0.93138172 -1.23437948  0.3738543  -1.11623799  0.80175312]
 [-0.48272377 -0.02184726  0.19510358  0.12452043 -0.62428776]
 [-0.39102034 -0.03578222 -0.53378259  1.41025141 -1.78153381]
 [-1.50623465  3.15629357  1.15453189  0.34136357  0.9432134 ]]
rdnint_one: 
 92
rdnint_more: 
 [46 34 58 77 57 49 26 98 83 69]


## Array Attributes and Methods

In [28]:
# Ne vom genera doua matrici cu care sa lucram in continuare
arr = np.arange(25)
arr_rdn = np.random.randint(0,50,10)

print("arr: \n", arr)
print("arr_rdn: \n", arr_rdn)

arr: 
 [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24]
arr_rdn: 
 [32  7 35 38 11 35 28 37 49 23]


In [29]:

# These are useful methods for finding max or min values. 
# Or to find their index locations using argmin or argmax

# max,min,argmax,argmin 

print("arr_rdn.max(): ", arr_rdn.max())
print("arr_rdn.argmax(): ", arr_rdn.argmax())

print("arr_rdn.min(): ", arr_rdn.min())
print("arr_rdn.argmin(): ", arr_rdn.argmin())


arr_rdn.max():  49
arr_rdn.argmax():  8
arr_rdn.min():  7
arr_rdn.argmin():  1


In [30]:
# Reshape - Returns an array containing the same data with a new shape.
arr_rsh = arr.reshape(5,5)
print ("arr_rsh: \n", arr_rsh)

# Shape - Shape is an attribute that arrays have (not a method):

arr.shape # Vector


arr_rsh: 
 [[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]


(25,)

In [32]:
# Notice the two sets of brackets
print(arr.reshape(1,25))

print(arr.reshape(1,25).shape)

print(arr.reshape(25,1))

print(arr.reshape(25,1).shape)

[[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
  24]]
(1, 25)
[[ 0]
 [ 1]
 [ 2]
 [ 3]
 [ 4]
 [ 5]
 [ 6]
 [ 7]
 [ 8]
 [ 9]
 [10]
 [11]
 [12]
 [13]
 [14]
 [15]
 [16]
 [17]
 [18]
 [19]
 [20]
 [21]
 [22]
 [23]
 [24]]
(25, 1)


In [33]:
# dtype - You can also grab the data type of the object in the array:

arr.dtype

dtype('int32')

Universal Array Functions 

In [34]:
1/arr # Also warning, but not an error instead infinity
arr**3
#Taking Square Roots
np.sqrt(arr)

#Calcualting exponential (e^)
np.exp(arr)

np.sin(arr)

np.log(arr)

C:\Users\Florea.Camelia\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in true_divide
  """Entry point for launching an IPython kernel.
C:\Users\Florea.Camelia\Anaconda3\lib\site-packages\ipykernel_launcher.py:11: RuntimeWarning: divide by zero encountered in log
  # This is added back by InteractiveShellApp.init_path()


array([      -inf, 0.        , 0.69314718, 1.09861229, 1.38629436,
       1.60943791, 1.79175947, 1.94591015, 2.07944154, 2.19722458,
       2.30258509, 2.39789527, 2.48490665, 2.56494936, 2.63905733,
       2.7080502 , 2.77258872, 2.83321334, 2.89037176, 2.94443898,
       2.99573227, 3.04452244, 3.09104245, 3.13549422, 3.17805383])

## Great Job!

That's all we need to know for now!